### ISSUE TITLE
Upgrade examples to setup-java V2

### ISSUE THREAD

**Issue by sormuras** [sormuras/download-jdk#17]
See https://github.com/actions/setup-java/pull/132 for details, especially https://github.com/actions/setup-java/pull/132#issuecomment-797431458.

Diff: https://github.com/sormuras/download-jdk/compare/main...dmitry-shibanov:test-setup-java@v2

**Comment by maxim-lobanov** [comment]
I suggest waiting a couple of weeks until `v2` is released.
We are going to push all changes to `v2-preview` branch on Monday and proceed with stable release in a couple of weeks.

**Comment by sormuras** [comment]
I'll create test workflow using `v2-preview` as described in

https://github.com/actions/setup-java/pull/132#issuecomment-799313072
