### ISSUE TITLE
Offer stable shorthands that reference latests builds

### ISSUE THREAD

**Issue by nipafx** [sormuras/download-jdk#22]
It would be great if the newest versions could be referenced by shorthand instead of their specific number, e.g.:

* `upcoming` for the next release - 17 at the moment
* `latest` for the latest build - 18 at the moment

Maybe there are more?

**Comment by aepfli** [comment]
i would also suggest:

- `stable` or `current` for the current release - 16 at the moment
- `lts` for the long term support release - 11 at the moment (i hope that is correct :D)

**Comment by sormuras** [comment]
Here, I don't like shorthands for two reasons:

- Having an explicit feature version (`9`..`18`) or project name (e.g. `Loom`) makes it easy to see, which actual JDK version will be downloaded: WYSIWYG-style
- I don't want to invent/define and maintain such shorthands in this action. Parsing and maintaining the [`9`..`18` list](https://github.com/sormuras/bach/blob/master/install-jdk.properties) from the HTML code of https://jdk.java.net is enough extra work already.

If there were shorthands urls like ...

- https://jdk.java.net/upcoming
- https://jdk.java.net/latest
- https://jdk.java.net/stable
- https://jdk.java.net/you-name-it

... they would be supported as of today. The same way how `Loom` & friends handled on-the-fly.

Or even better, someone with access to https://jdk.java.net should implement something like proposed here: https://mail.openjdk.java.net/pipermail/web-discuss/2018-May/000533.html

**Comment by nipafx** [comment]
> makes it easy to see, which actual JDK version will be downloaded: WYSIWYG-style

I get what I see, but not what I want. 😉 For a Java 8 project, I don't want to build on 8, 11, 16, and 17/18. I want to build on my baseline, each LTS since then, the latest released, and the newest upcoming. The first two of those can't be shorthanded, but the last two can. So adding `current` and `latest` to the build config is both more expressive (because I don't care about the particular versions) and easier (don't have to remember to update and then actually do it).

> I don't want to invent/define and maintain such shorthands in this action.

I understand that. But if you don't _everybody else_ has to muck with their build configuration every few months. The needs of the many outweigh the needs of the few - in this case you. 😜

**Comment by sormuras** [comment]
I hear what you want, but I am still waiting for a machine-readable index of some kind hosted at https://jdk.java.net 🤓

See and follow links in https://mail.openjdk.java.net/pipermail/web-discuss/2021-April/000589.html for details.

**Comment by sormuras** [comment]
Ah, here we go: https://www.oracle.com/java/technologies/jdk-script-friendly-urls/

Thus, supporting `latest` is a thing now.

**Comment by sormuras** [comment]
Might be tackled in https://github.com/oracle-actions/setup-java
