### ISSUE TITLE
Failing action due to FileNotFoundException: https://github.com/sormuras/bach/raw/master/install-jdk.properties

### ISSUE THREAD

**Issue by rinatigati** [sormuras/download-jdk#25]
This is similar to #13 but new. Looks like due to changes in the `bach` repository, this action is failing again:

```
Run sormuras/download-jdk@v1
Run echo "::set-output name=file::JDK_ARCHIVE_NOT_DOWNLOADED_YET"
Download JDK 18 (linux-x6[4](https://github.com/rinatigati/CodeKatas/runs/5471267500?check_suite_focus=true#step:3:4))
Exception in thread "main" java.io.FileNotFoundException: https://github.com/sormuras/bach/raw/master/install-jdk.properties
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1[9](https://github.com/rinatigati/CodeKatas/runs/5471267500?check_suite_focus=true#step:3:9)20)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
```

I also found the following action you've contributed to very recently: https://github.com/oracle-actions/setup-java

Should that action be used instead of this one? 

By the way, appreciate the work you've put into these actions. 😸

**Comment by sormuras** [comment]
Thanks for reporing this issue and the kind words, @rinatigati 

> I also found the following action you've contributed to very recently: https://github.com/oracle-actions/setup-java
> Should that action be used instead of this one?

Yes. At least for Oracle JDK 17 and later and OpenJDK GA and EA builds built by Oracle. Inluding JDK18 as of today — what seems to be the release your project wants to install.

Having said that, I'll update this action to load the soon outdated `install-jdk.properties` file. Some of the URLs stored there will continue to work as-is.
